### ISSUE TITLE
access via alternate ids not working

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#596] opened 2014-11-25 18:23 UTC
accessing this page:
http://tartini.crbs.ucsd.edu/phenotype/HP:0000004

doesn't work.  but it's a real identifier (although perhaps deprecated).  we need to be able to get to it.

here's the term, you can see it is an alt id:
http://www.human-phenotype-ontology.org/hpoweb/showterm?id=HP:0000004

the page should probably be directed to the current id:
http://tartini.crbs.ucsd.edu/phenotype/HP:0012823

**Comment by kshefchek** [comment] 2015-07-02 20:48
Duplicate of #643, closing this one since the other has more info.

**Closed as completed by kshefchek** 2015-07-02 20:48 UTC
Labels: bug, duplicate
