### ISSUE TITLE
Examples of search for new users

### ISSUE THREAD

**Issue by selewis** [monarch-initiative/monarch-legacy#573] opened 2014-10-26 17:39 UTC
The front page search box needs to have some exemplary examples. First thing you want to do is give brand-new users an immediate means of trying it out, examples that showcase the functionality. Plus don't want them picking examples that fail because of current lack of data.

**Comment by jmcmurry** [comment] 2015-10-13 05:38
This is still relevant but a duplicate of other more detailed or recent tickets.

**Closed as completed by jmcmurry** 2015-10-13 05:38 UTC
Labels: web site front end
