### ISSUE TITLE
Reactome link update

### ISSUE THREAD

**Issue by TomConlin** [monarch-initiative/monarch-legacy#1533] opened 2018-01-18 22:23 UTC
On the Pathways tab

https://monarchinitiative.org/gene/NCBIGene:125#pathways

links to Reactome   for example  "Ethanol oxidation"  

https://reactome.org/cgi-bin/eventbrowser_st_id?ST_ID=REACT_R-HSA-71384

result in a page not found error

Reactome does have  page for "Ethanol oxidation" at 

https://reactome.org/content/detail/R-HSA-71384

**Comment by jmcmurry** [comment] 2018-01-18 22:53
this is an xref issue; it could be that reactome changed the URIs. The appropriate stanza to fix is here:
https://github.com/monarch-initiative/monarch-app/blob/master/conf/xrefs.json#L569
Though I would want to first make sure there are not issues with type-polymorphic paths that would require polymorphic prefixes.

**Comment by kshefchek** [comment] 2018-01-19 17:44
Dupe of https://github.com/monarch-initiative/monarch-app/issues/1518

**Closed as completed by kshefchek** 2018-01-19 17:44 UTC
