### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by davism84** [monarch-initiative/monarch-legacy#893] opened 2015-08-05 17:38 UTC
fyi  I did a fresh installation and got the following error:  @kshefchek

> jsdoc@3.3.0-alpha5 postinstall /home/i2b2demo/async-test/monarch-app/node_modules/gulp-jsdoc/node_modules/jsdoc
> node ./node/postinstall.js

npm ERR! cb() never called!
npm ERR! not ok code 0

Error: Cannot find module 'array-uniq'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/i2b2demo/async-test/monarch-app/node_modules/gulp/node_modules/gulp-util/lib/PluginError.js:3:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/i2b2demo/async-test/monarch-app/node_modules/gulp/node_modules/gulp-util/index.js:17:16)

**Comment by jmcmurry** [comment] 2015-08-05 21:16
I don't know if it is a related issue or not, but I got an install error just now too.

```
Error: failed to list directory node_modules/phenogrid/dist
        at fs.js:729 (list)
        at pup-tent/pup-tent.js:177 (anonymous)
        at pup-tent/pup-tent.js:274 (anonymous)
        at underscore/underscore.js:103 (anonymous)
        at pup-tent/pup-tent.js:270 (anonymous)
        at lib/monarch/web/webapp.js:21
        at lib/monarch/web/webapp_launcher.js:5
        at /Users/jmcmurry/code/monarch/monarch-app/lib/monarch/web/webapp_launcher_dev.js:9
```

However, it was addressed by deleting the `node_modules` directory and doing `npm install` first.

**Comment by kshefchek** [comment] 2015-08-05 22:02
I'm not able to reproduce but will investigate.  @davism84 did you try clearing our your node_modules and re-installing?

**Comment by yuanzhou** [comment] 2015-08-13 18:40
I did the testing this morning and didn't see this error.

**Comment by DoctorBud** [comment] 2015-10-08 09:48
Please close this ticket (I don't have permissions). Most of the above errors have long since been fixed.

**Closed as completed** 2015-10-09 01:30 UTC
Labels: bug, nodejs
