### ISSUE TITLE
seeing equivalent classes in autocomplete

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#902] opened 2015-08-08 16:10 UTC
here we have two 'cleft palate' from mondo and two from HPO/MP. This is confusing.

<img width="581" alt="screen shot 2015-08-08 at 9 08 03 am" src="https://cloud.githubusercontent.com/assets/796636/9151143/1d5ea404-3dad-11e5-8dfa-5899836b8707.png">

**Comment by kshefchek** [comment] 2015-08-08 17:45
This is just the state of things since we can't filter out equivalencies without taking a performance hit.  What would be the ideal view here?  It may be useful to keep equivalent phenotypes, but I'm guessing we need to need uniquify diseases coming from mondo.  We could filter out duplicate labels for diseases and phenotypes.  We had previously done this for all autocompleted items but I removed this as it was removing genes.

**Comment by cmungall** [comment] 2015-08-08 19:12
Multiple things here:
1. Label redundancy between diseases and phenotypes. These are not and should not be declared equivalents. But we should at least have some other defining relationship between them, and I would love to force global label uniqueness but neither side will budge
2. Equivalency between phenotypes (mostly MP, HP). We do not take an aggressive merge strategy here; we could. Until we do, seeing both MP and HP is expected behavior
3. Equivalency between diseases. We _do_ take an aggressive merge strategy here, so if there are apparent redundancies, then this is a mondo issue. Unfortunately this is not straightforward. See https://github.com/monarch-initiative/human-disease-ontology/issues/41

**Comment by jmcmurry** [comment] 2015-10-07 18:27
Autocomplete on beta is definitely an improvement relative to production (wherein lots of (ostensibly) duplicated terms). However, there are still duplicated terms for all three reasons @cmungall described above. Although we _could_ further disambiguate (HP/MP etc,) but I worry that we might be already trying to accomplish too much in the autocomplete feature itself. The search box is one the users first experiences with the site and really important to do well.

The problem is perhaps best illustrated by searching on a gene symbol. If I want to see all evidence relevant to Pax2, I have execute (and mentally integrate) some dozen separate queries, one for each species. I have no way to merge the evidence into one view.

![screen shot 2015-10-06 at 22 38 13](https://cloud.githubusercontent.com/assets/3658863/10329833/f967574c-6c7a-11e5-8ee9-1818d3ea1341.png)

If an element isn't selected from the autocomplete dropdown, the search results page is very unhelpful. In fact, it doesn't give you a whole lot more than autocomplete does; I haven't looked but suspect they're even served from the same backend. Here's an example.

![screen shot 2015-10-06 at 22 39 20](https://cloud.githubusercontent.com/assets/3658863/10329845/24a2c28e-6c7b-11e5-9c2e-0328b5a36579.png)

Similarly, if I'm interested in cleft palate, I probably don't care (at first) whether it is categorized as a disease or a phenotype, and I probably don't care whether it is HP or MP, I just want to see all the evidence meaningfully grouped in one place where I can drill down from there. 

![screen shot 2015-10-06 at 22 40 09](https://cloud.githubusercontent.com/assets/3658863/10329856/5ad1feec-6c7b-11e5-800d-c602e18fb001.png)

Would you guys be open to aggressive merging (text) in the autocomplete box, with the idea that the user, upon selecting from autosuggest, would _always_ be sent to a search results list instead of a directly to a specific Monarch record. I have some thoughts about how we might represent search results list to the user, but would like to talk with users directly. I also don't want to explore too far without a better understanding of how we got to where we are now and what the limitations might be on the backend and performance. Thoughts welcome here in issue tracker, but even better would be if we could talk about it during tomorrow's UI call.

**Comment by kshefchek** [comment] 2015-10-07 19:43
Looks like theres a bug somewhere as these should be collapsing as one phenotype and one disease, I'll look into it.

**Comment by kshefchek** [comment] 2015-10-07 19:55
Apparently these two cleft palate disease IDs are not equivalents in the ontology, see

http://kato.crbs.ucsd.edu:9000/scigraph/graph/neighbors?id=OMIM:119540&id=DOID:674&depth=5&blankNodes=false&relationshipType=equivalentClass&direction=BOTH&project=*

However, the two phenotypes are equivalent, but this looks like an issue with the latest scigraph load with the equivalency merging, compare:

http://kato.crbs.ucsd.edu:9000/scigraph/graph/neighbors?id=HP:0000175&depth=5&blankNodes=false&relationshipType=equivalentClass&direction=BOTH&project=*

to 

http://geoffrey.crbs.ucsd.edu:9000/scigraph/graph/neighbors?id=HP:0000175&depth=5&blankNodes=false&relationshipType=equivalentClass&direction=BOTH&project=*

@jnguyenx is this expected?  For some reason I thought the equivalentClass relationships remain and the rest are removed when collapsing the classes.

**Comment by jmcmurry** [comment] 2015-10-07 20:35
Thanks for exploring this, @kshefchek, however, the larger issue is whether we should be displaying the granularity in autocomplete list at all. Currently, on beta, autocomplete is completely broken for me. If I type `cleft p` in the box and wait 45 seconds, all I see is the spinner, but no list of suggestions. If we back away from having richness within the autocomplete, and instead have a bag of (aggressively merged) text-only terms with no categorization, my hunch is that autocomplete will be faster and more reliable. The existing autocomplete widget would be useful in the context of term selection (eg. by curators annotating data); however, when searching for data, I am not sure that the current autocomplete implementation is the right one. Thoughts welcome...

**Comment by kshefchek** [comment] 2015-10-07 20:49
I believe @jnguyenx is reloading our beta scigraph instance related to the bug above so all vocab services are offline at the moment, I'll switch the configuration for beta so that we're pointing to the staging server.

**Closed as completed** 2015-10-27 15:27 UTC
Labels: enhancement, web site front end, search, merge differentiate or group, species
