### ISSUE TITLE
some diseases still don't have labels

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#858] opened 2015-07-25 23:49 UTC
e.g. http://beta.monarchinitiative.org/disease/Orphanet:90120

(thought this should be fixed with latest mondo load but maybe not loaded yet?)

**Comment by cmungall** [comment] 2015-07-26 00:58
Dupe of #852

**Comment by jmcmurry** [comment] 2015-10-13 16:18
Closing as this has been addressed and is a duplicate.

**Closed as completed by jmcmurry** 2015-10-13 16:18 UTC
Labels: duplicate
