### ISSUE TITLE
add species labels to genes in autocomplete

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#877] opened 2015-08-02 15:07 UTC
When you autocomplete, we should show in parentheses which species the gene is from. 

Eg. SOX9 (gene, human) rather than just the category (gene)

Alternatively, we could have an uber-Sox9 gene results page and allow further specification from there. This might be preferable as we get more data from more species. This would mean only one Sox9 in the autocomplete.

**Comment by cmungall** [comment] 2015-08-03 00:06
#851 
For the uber sox9, should we just make the human a proxy for it?

**Comment by kshefchek** [comment] 2015-08-03 16:00
Duplicate of #865

**Comment by kshefchek** [comment] 2015-08-03 16:01
For this, #851 and #865 we will need to add taxon as a node property.  Working with @ccondit to do this in a way that keeps SciGraph domain agnostic (ie adding to a configuration file).  cc @jnguyenx

**Comment by ccondit** [comment] 2015-08-03 23:05
Does there need to be an option for the completion (ie only complete human gene symbols) or is this just for display purposes?

**Comment by kshefchek** [comment] 2015-08-03 23:08
I think as a first pass it would just be for display purposes, although it could be useful to filter if we don't have much information for one or more species.

**Comment by jmcmurry** [comment] 2015-10-09 19:29
This is now working on beta, so I will close it.  Related to issues labeled [search](https://github.com/monarch-initiative/monarch-app/labels/search)

**Closed as completed** 2015-10-09 19:29 UTC
Labels: duplicate, search, merge differentiate or group, species, neighborhood
