### ISSUE TITLE
multi input comparison

### ISSUE THREAD

**Issue by davism84** [monarch-initiative/monarch-legacy#644] opened 2015-02-02 18:45 UTC
we need a search call that runs like /simsearch, but acts on a specific set of targets. Given a set of input phenotypes p1…pn, and models m1..mn, this will run owlsim for those phenotypes, but only against the provided set of models. 

There are two use cases:
1. Drilling down into strains for specific genotypes.
2. Running a similarity search against specific genes as identified by exomiser.

**Comment by nlwashington** [comment] 2015-02-02 19:20
shall i make the assumption that the queries will be performed as follows (where entities are diseases/genes/genotypes/etc that can be mapped to a list of phenotypes each):
1.  entity vs entities(1..n)
2.  a list of phenotypes against a list of target entities
3.  a list of phenotypes vs a list of phenotypes

(1) can be done now.  (2) and (3) are not yet implemented.  i am making the assumption that we will NOT be implementing:
(4) a list of phenotypes vs a list of a list of phenotypes nor 
(5) a list of entities vs a list of entities (requiring the the cross-product)

@davism84 and @cmungall, will addition of (2) and (3) suffice?

**Comment by harryhoch** [comment] 2015-02-02 19:37
Mike, isn’t #2 exactly what we need?

On Feb 2, 2015, at 2:20 PM, Nicole Washington <notifications@github.com<mailto:notifications@github.com>> wrote:

shall i make the assumption that the queries will be performed as follows (where entities are diseases/genes/genotypes/etc that can be mapped to a list of phenotypes each):
1. entity vs entities(1..n)
2. a list of phenotypes against a list of target entities
3. a list of phenotypes vs a list of phenotypes

(1) can be done now. (2) and (3) are not yet implemented. i am making the assumption that we will NOT be implementing:
(4) a list of phenotypes vs a list of a list of phenotypes nor
(5) a list of entities vs a list of entities (requiring the the cross-product)

@davism84https://github.com/davism84 and @cmungallhttps://github.com/cmungall, will addition of (2) and (3) suffice?

—
Reply to this email directly or view it on GitHubhttps://github.com/monarch-initiative/monarch-app/issues/644#issuecomment-72519231.

---

Harry Hochheiser
University of Pittsburgh
Department of Biomedical Informatics
harryh@pitt.edumailto:harryh@pitt.edu  412 648 9300

**Comment by davism84** [comment] 2015-02-02 19:57
Yes #2 is what we need.

**Comment by nlwashington** [comment] 2015-02-02 20:46
At the moment, you can query with a list of phenotypes, and list of target entities, each delimited with the plus sign, like:
http://tartini.crbs.ucsd.edu/compare/MP:0000243+MP:0004994+MP:0001312/NCBIGene:13014+OMIM:254800
this example will return to you the comparison of the set of MP phenotypes vs each target (in this case the gene and the disease) individually.
this has the unusual consequence that if your target is a (list of) phenotype term(s), it will still split them up and then compare the set of phenotypes in the query vs each phenotype individually.  (i imagine we don't want this behavior, but we need to decide how we want a list of targets vs a list of phenotypes to represent a single target to be encoded).
if this doesn't satisfy your needs please let me know.
there are some assumptions being made in the app code right now regarding how to "type" the targets; figuring out the type of the target is necessary in order to fetch the phenotype associations.  there is some simple mapping code, but may be insufficient in the case of targets with the MGI prefix, as it makes the assumption that MGI prefixes are genes (but technically they could be genotypes or alleles or any number of things).  once we get SciGraph loaded with everything, this will fix itself.  please add bugs to the tracker if you are unable to acquire the target phenotypes.

**Comment by nlwashington** [comment] 2015-02-02 21:02
also, if you query with multiple entities (like two genes or two diseases), it will create a union of the phenotypes from the two entities as the profile.  this will come in handy when wanting to query with both phenotypes and diseases (as in the current functionality of the "analyze" phenotypes page).  in commit 431f38a

**Comment by harryhoch** [comment] 2015-02-03 03:21
Nicole, as I read the engine.compareEntities(x,y) call,
it takes query_id (x) "One of: IRI string, OBO-style ID or NIF-style” and  as
target_id (y), "Either a single identifier, or an array of identifiers.”  So, the input query can only be a single item, which is then immediately blown up in to a list of phenotypes.

Mike is going to try to rewrite this to take a list of items for x.  This shouldn’t be hard. Any reason why it wouldn’t work?

On Feb 2, 2015, at 4:02 PM, Nicole Washington <notifications@github.com<mailto:notifications@github.com>> wrote:

also, if you query with multiple entities (like two genes or two diseases), it will create a union of the phenotypes from the two entities as the profile. this will come in handy when wanting to query with both phenotypes and diseases (as in the current functionality of the "analyze" phenotypes page). in commit 431f38ahttps://github.com/monarch-initiative/monarch-app/commit/431f38a674ed7de12f82e02a7059c18d54e83429

—
Reply to this email directly or view it on GitHubhttps://github.com/monarch-initiative/monarch-app/issues/644#issuecomment-72536998.

---

Harry Hochheiser
University of Pittsburgh
Department of Biomedical Informatics
harryh@pitt.edumailto:harryh@pitt.edu  412 648 9300

**Comment by nlwashington** [comment] 2015-02-03 04:50
I already implemented this today (see above) in commits 16d79a5 and 431f38a, but i failed to update the documentation for the function.  I will update it tomorrow.

**Comment by harryhoch** [comment] 2015-02-03 13:48
Great, thanks! Mike, please note and look at Nicole’s changes.

> On 2 Feb 2015, at 11:50 PM, Nicole Washington notifications@github.com wrote:
> 
> I already implemented this today (see above) in commits 16d79a5 and 431f38a, but i failed to update the documentation for the function. I will update it tomorrow.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Harry Hochheiser
University of Pittsburgh
Department of Biomedical Informatics 
harryh@pitt.edu         412 648 9300

**Comment by nlwashington** [comment] 2015-02-03 18:45
I have updated the documentation in commit aeeadd1.  Mike, please close this ticket when you've tested it's functionality and it satisfies your requirements.

**Comment by davism84** [comment] 2015-02-03 21:44
Nicole, I'm getting a TypeError: Cannot read property "0.0" from undefined (lib/monarch/api.js, line 5682),  when I issue the following:  http://tartini.crbs.ucsd.edu/compare/HP:0000003+HP:0009726/NCBIGene:393816

**Comment by nlwashington** [comment] 2015-02-03 22:24
ok, the error should be fixed now. when supplying a set of phenotypes as the query, a plus-delimited label is constructed.

**Comment by davism84** [comment] 2015-02-09 14:01
I'm getting the following error:

Proxy Error

The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /compare/MP:0000243+MP:0004994+MP:0001312/NCBIGene:13014+OMIM:254800.

Reason: Error reading from remote server

Apache/2.2.15 (CentOS) Server at tartini.crbs.ucsd.edu Port 80

http://tartini.crbs.ucsd.edu/compare/MP:0000243+MP:0004994+MP:0001312/NCBIGene:13014+OMIM:254800

**Comment by nlwashington** [comment] 2015-02-23 23:58
@davism84 the query you posted above works.  however, i think that longer queries (with many more pheno ids) fails with the proxy error.  i'm testing this now.

**Comment by harryhoch** [comment] 2015-02-27 14:42
@nlwashington,  here’s a query that fails for us:

http://tartini.crbs.ucsd.edu/compare/MP:0000243+MP:0004994+MP:0001312/NCBIGene:13014+OMIM:254800+OMIM_255800+OMIM_123500+OMIM_604757+OMIM_218600+OMIM_123100+OMIM_176943+OMIM_134934

Note two aspects of the failure:
1. increasing the number of models leads to failure, more so than the # of phenotypes
2. This generally works better on a second try. My guess is that this would be because some results might be cached at that point?

Given the correlation between the number of models and the error, one hypothesis would be that the separation of the call into n distinct owlsim calls is the problem.  Fixing this might require some reconsideration of the plumbing..

> On 23 Feb 2015, at 6:58 PM, Nicole Washington notifications@github.com wrote:
> 
> @davism84 the query you posted above works. however, i think that longer queries (with many more pheno ids) fails with the proxy error.  i'm testing this now.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Harry Hochheiser
University of Pittsburgh
Department of Biomedical Informatics 
harryh@pitt.edu         412 648 9300

**Comment by davism84** [comment] 2015-03-06 21:17
@nlwashington this is causing a TypeError

http://tartini.crbs.ucsd.edu/compare/HP_0008734+HP_0003202+HP_0002750+HP_0000518+HP_0000396+HP_0004322+HP_0000347/ZDB-ALT-120411-457+ZDB-ALT-980203-1221+ZDB-ALT-980203-1560

**Comment by kshefchek** [comment] 2015-03-06 21:31
Looks like an issue with mapGeneToNCBIgene(), should be fixed now.

**Comment by cmungall** [comment] 2015-07-24 22:09
is this fixed?

**Comment by harryhoch** [comment] 2015-07-25 04:04
No, but I'm not sure if the problem has changed. 
/compare calls engine.compareEntities(), which eventually leads to a call like 

FETCHING: http://geoffrey.crbs.ucsd.edu:9000/scigraph/graph/ZDB-ALT-120411-457+ZDB-ALT-980203-1221+ZDB-ALT-980203-1560.json, which 404s. Should it?

**Comment by jmcmurry** [comment] 2015-10-08 17:46
Just want to refresh Harry's question; what is the status?

**Comment by kshefchek** [comment] 2015-10-08 18:01
I've been refactoring the compare function to remove dependencies on NIF and noticed the same thing as @harryhoch, when grouping targets with a plus sign the call fails.  When listing with a comma the call will work.

This issue is this line: https://github.com/monarch-initiative/monarch-app/blob/9bcc462c/lib/monarch/api.js#L4329 where we concatenate any IDs with a plus sign and send this to scigraph.  This will return an empty graph from scigraph and result in the rest of code failing.

@nlwashington what is the intended behavior when grouping targets with a plus sign?  Any chance you could point me to a commit when this code was working?

**Comment by nlwashington** [comment] 2016-01-22 19:32
back to harry's question, should the call to scigraph like `...scigraph/graph/ZDB-ALT-120411-457+ZDB-ALT-980203-1221+ZDB-ALT-980203-1560.json` result in a 404?

the answer is yes because that is not an identifier for any entity in our system.  also, it isn't a real identifier in the way we need it, as it isn't in the curie format.

note the call originated from 
http://monarchinitiative.org/compare/HP_0008734+HP_0003202+HP_0002750+HP_0000518+HP_0000396+HP_0004322+HP_0000347/ZDB-ALT-120411-457+ZDB-ALT-980203-1221+ZDB-ALT-980203-1560

there are several things to consider here:
1.  the phenotype ids have an underscore (we've moved away from those underscores).  i looked at the monarch-app logs, and it doesn't seem to deal with these any more. please replace `HP_` with `HP:`
2.  the thing that is being compared is not in CURIE format.  the monarch-app will have no idea what to do with that
3.  i'm not sure what the intended comparison is supposed to be.  regardless, you need to prefix the `ZDB-ALT` with `ZFIN:` in all cases.  here's options about how to fix:
  a.  if you mean to compare the list of HP ids vs the union of phenotypes that are annotated to three alleles, then keep the join with the plus sign.  this will return one comparison result.
http://monarchinitiative.org/compare/HP:0008734+HP:0003202+HP:0002750+HP:0000518+HP:0000396+HP:0004322+HP:0000347/ZFIN:ZDB-ALT-120411-457+ZFIN:ZDB-ALT-980203-1221+ZFIN:ZDB-ALT-980203-1560
  b.  if you mean to make three comparisons, one each between the list of HP ids and the resulting phenotype sets from each allele, then change the second item to be delimited with commas.  it would look like:
http://monarchinitiative.org/compare/HP:0008734+HP:0003202+HP:0002750+HP:0000518+HP:0000396+HP:0004322+HP:0000347/ZFIN:ZDB-ALT-120411-457,ZFIN:ZDB-ALT-980203-1221,ZFIN:ZDB-ALT-980203-1560
(note that i seem to only get one result back, because only ZFIN:ZDB-ALT-980203-1560 has any phenotypes anyway)
4.  the identifier that is created as a result of a concatenated list given to owlsim will never be in the scigraph instance.  it is just passed through from owlsim back to monarch.  since the node isn't found in scigraph, perhaps phenogrid can deal with this gracefully and not create a link?

**Comment by harryhoch** [comment] 2016-01-22 19:37
Thanks, Nicole. Given the age of this issue, and the fact that we've moved forward with the genotype expansion, I think this is probably a closed issue. I think we should close it off and refer back to your notes if there are any questions that arise. ok? Please reopen if not.

**Closed as completed by harryhoch** 2016-01-22 19:37 UTC
Labels: api and exports, owlsim, search, identifiers
