### ISSUE TITLE
Analyze phenotypes: autocomplete synonym behavior

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-legacy#1303] opened 2016-07-11 21:33 UTC
Much of what I've mentioned previously about autocomplete behavior in the homepage applies to it in the context of Analyze Phenotypes.

We should be showing whatever it is that matches the entered text, if that is a synonym, it should show. In this case the match is for "Farsightedness" but you'd never know it.

<img width="335" alt="screen shot 2016-07-11 at 2 30 49 pm" src="https://cloud.githubusercontent.com/assets/3658863/16747518/450c48c2-4774-11e6-8a3d-f9465e1cfabc.png">

**Comment by jmcmurry** [comment] 2016-07-11 21:41
[Developmental delay](https://monarchinitiative.org/phenotype/HP%3A0001263) is a valid human phenotype, however, does not appear to be an option in the phenotype profile entry. 
I might suggest that if there's an exact matching synonym, that be the thing that is shown, rather than the primary label. If the above behavior is achieved, this may be a non-issue.

<img width="293" alt="screen shot 2016-07-11 at 2 36 54 pm" src="https://cloud.githubusercontent.com/assets/3658863/16747826/8f830700-4775-11e6-98e6-7c213419f1be.png">

**Comment by harryhoch** [comment] 2016-07-12 01:09
+1 - this is a modeling issue, and I think perhaps a golr issue. @kshefchek, is that right?

**Comment by kshefchek** [comment] 2016-07-12 06:39
Correct, which is why I've proposed we consider an index specifically for search and autocomplete requirements, see https://github.com/monarch-initiative/monarch-app/issues/1210

**Comment by kshefchek** [comment] 2016-07-14 17:26
This is also important for genes, I've noticed this happening with the latest NCBI gene build, for example:
![screenshot from 2016-07-14 10 21 38](https://cloud.githubusercontent.com/assets/1467299/16849018/5d5e2cd4-49ad-11e6-9af4-d137e9f896e7.png)
![screenshot from 2016-07-14 10 22 17](https://cloud.githubusercontent.com/assets/1467299/16849021/5f612586-49ad-11e6-9b3f-455036ffeaea.png)

**Comment by harryhoch** [comment] 2016-07-14 17:39
@kshefchek, let's try to discuss during the scrum this afternoon

**Comment by kshefchek** [comment] 2018-08-22 23:54
duplicate of https://github.com/monarch-initiative/monarch-app/issues/1510 (more info there) and fixed with biolink and alpha.

**Closed as completed by kshefchek** 2018-08-22 23:54 UTC
Labels: Analyze Phenotypes
