### ISSUE TITLE
Invalid NCBI gene IDs

### ISSUE THREAD

**Issue by zhengj2007** [monarch-initiative/monarch-legacy#1482] opened 2017-08-11 01:18 UTC
We retrieved all gene and disease associations from Solr server. We found 485 genes that are reported as being NCBI gene IDs but cannot be found within ncbi including taxon. 

The list of gene we cannot find is on:
https://docs.google.com/spreadsheets/d/1GtM8ufJTpb46PO5SknUEQ5ITHck7IbRRpKofSd0Aazs/edit?usp=sharing

In the issue tracker, https://github.com/monarch-initiative/monarch-app/issues/1450#issuecomment-309840484
It said that "There are a few IDs in Monarch that were perhaps generated in error with the assumption that if we encountered a numeric ID that it was from NCBI." 

We'd like to know whether these invalid NCBI gene IDs are generated in error that we should ignore. If so, is the gene label correct that we can count on it to find out NCBI gene ID?

Thanks!

**Comment by kshefchek** [comment] 2017-08-11 21:34
I believe these are all from OMIA, there is a ticket here referencing the gene issue: https://github.com/monarch-initiative/dipper/issues/226

**Comment by kshefchek** [comment] 2017-08-11 21:36
Closing as a duplicate of monarch-initiative/dipper#226, @zhengj2007 I have cc'ed you there.

**Closed as completed by kshefchek** 2017-08-11 21:36 UTC

**Comment by lwinfree** [comment] 2017-08-11 22:12
Hi Jie,

Yes those 485 genes should be ignored. We are working on fixing this, as
Kent noted in Issue monarch-initiative/dipper#226
<https://github.com/monarch-initiative/dipper/issues/226>. Please follow
along for updates.
Thanks!

**Comment by zhengj2007** [comment] 2017-08-12 00:46
@lwinfree @kshefchek 

Thanks a lot for your reply. We will follow up the updates on Issue: monarch-initiative/dipper#226
