### ISSUE TITLE
'homo sapiens' should be capitalized

### ISSUE THREAD

**Issue by balhoff** [monarch-initiative/monarch-legacy#1224] opened 2016-04-09 02:17 UTC
On many pages (e.g. https://beta.monarchinitiative.org/disease/DOID:863), the human label 'homo sapiens' appears. This should be capitalized as 'Homo sapiens'. I'm reporting this here because I'm not sure where this is specified.

**Comment by cmungall** [comment] 2016-04-13 18:45
SciGraph-ontology is correct:

https://scigraph-ontology.monarchinitiative.org/scigraph/graph/neighbors/NCBITaxon:9606?depth=0

The source of this is monarch.owl, so all is good with monarch.owl

The problem arises in scigraph-data, which is a larger graph encompassing all data ttl files:

https://scigraph-data.monarchinitiative.org/scigraph/graph/neighbors/NCBITaxon:9606?depth=0

Which means we end up selecting an arbitrary one (often wrong) for golr:

https://solr-dev.monarchinitiative.org/solr/golr/select/?q=subject_closure:%22DOID:863%22&wt=json
https://solr-dev.monarchinitiative.org/solr/golr/select/?q=subject_closure:%22NCBIGene:10059%22&wt=json

We are getting better at sourcing evidence for edges. But unlike in RDF, in Neo4J, a property-value isn't an edge, and so doesn't have edge properties. 

Ideally for https://scigraph-data.monarchinitiative.org/scigraph/graph/neighbors/NCBITaxon:9606?depth=0

For these two axioms:

```
"http://www.w3.org/2000/01/rdf-schema#label": [

    "homo sapiens",
    "Homo sapiens"

],
```

we would have axiom annotations with their source.

But that's not really practical. However, we should at least have some more metadata even if it isn't per axiom. For example, a field like `sources` that includes the purls for the ttls from which this was derived.

In this case I assume the cause is that some ttl is asserting inappropriate labels for taxa, and when @jnguyenx merges cliques somehow the good one is not prioritized

**Comment by cmungall** [comment] 2016-04-13 18:54
Note we have essentially the same issue dotted around the trackers:

https://github.com/monarch-initiative/dipper/issues/282

We should fix this upstream but also be defensive, e.g.
- [ ] take care in dipper to exclude inclusion of derived assertions that are redundant with a source we already bring in
- [ ] have better checks to ensure we are doing this
- [ ] have more sophisticated configurations for label and other metadata selection when clique merging
- [ ] better transparency of the whole chain

**Comment by jnguyenx** [comment] 2017-04-26 16:01
Was fixed in GENO

**Closed as completed by jnguyenx** 2017-04-26 16:01 UTC
Labels: bug, data, species
