### ISSUE TITLE
gene not showing up from genotypes in models

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#880] opened 2015-08-02 23:35 UTC
for this:
http://beta.monarchinitiative.org/model/Coriell:GM13707

we don't see the BRCA1 as a gene variant.  but this cell line does have a variant BRCA1 (OMIM:113705.0006).  
i can tell that the genotype is linked to the gene correctly:
http://beta.monarchinitiative.org/genotype/dbSNPIndividual:11864

also, it should have a disease listed:  OMIM:604370

@ccondit can you verify if the data is there and @kshefchek check on golr.

**Comment by kshefchek** [comment] 2015-08-03 17:21
I can't access it in GOlr, will check the cypher query.

**Comment by ccondit** [comment] 2015-08-03 23:03
Coriell:GM13707 is loaded on duckworth. I'm guessing it's a problem with the query.

**Comment by kshefchek** [comment] 2015-08-05 17:54
For the missing gene relationship see: https://github.com/monarch-initiative/monarch-app/issues/878#issuecomment-128087994
For disease: https://github.com/monarch-initiative/monarch-app/issues/881

**Comment by kshefchek** [comment] 2015-08-11 16:59
Closing as duplicate of  #878 (the fix there will fix both issues).

**Closed as completed by kshefchek** 2015-08-11 16:59 UTC
Labels: bug
