### ISSUE TITLE
missing homologs

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#1237] opened 2016-04-20 13:13 UTC
on this page:
https://monarchinitiative.org/gene/NCBIGene%3A494115
autocomplete shows additional species RBMXL1 but these are not on the homolog tab
@TomConlin @kshefchek @cmungall 

same on beta.

**Comment by cmungall** [comment] 2016-04-20 16:52
Tom, do you know how to go about debugging this?

First look at panther.ttl, we expect to find the HGNC ID in there. If 
it's not, further investigate and report upstream to panther

**Comment by TomConlin** [comment] 2016-04-20 18:45
panther dipper is producing HGNC identifiers in its output 
but HGNC:25073  was not produced in the run I have on hand from ~6 weeks ago.
the identifier does not exist in either of the raw input files we have

grep HGNC:25073  RefGenomeOrthologs
grep HGNC:25073  Orthologs_HCOP

will be in meetings for the next while

**Comment by TomConlin** [comment] 2016-04-22 22:10
On the panther website the HGNC identifier for RBMXL1 does exists now.
http://www.pantherdb.org/genes/gene.do?acc=HUMAN|HGNC=25073|UniProtKB=Q96E39
as a sparse looking record.  Nothing on the page indicates when it was added.

Will try building a current set of panther triples.

**Comment by jmcmurry** [comment] 2016-04-22 23:50
This thread reminded me to document the inherent complexity in HGNC identifiers. Just want to make sure we are aware of it https://github.com/prefixcommons/operations/issues/19

1) ambiguity about what identifier is
2) multiple entity types
3) multiple identifier types
4) Type-specific URL patterns combined with lack of deterministic typing in local ID

**Comment by TomConlin** [comment] 2016-04-23 00:35
Will note that after a failed search with an ideal identifier it is routine to repeat with  degenerate identifiers in an ad hoc fashion.

**Comment by TomConlin** [comment] 2016-04-23 01:09
rerunning with currently available data does not change anything w.r.t HGNC:25073

**Comment by kshefchek** [comment] 2016-06-03 00:26
This data is not in panther, so not a bug on our side.

**Closed as completed by kshefchek** 2016-06-03 00:26 UTC
