### ISSUE TITLE
Make REST API available via https

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-legacy#1194] opened 2016-02-29 22:01 UTC
I'm working on getting phenogrid on to ZFIN's disease term pages. I need to call the REST API to fetch HP ids for a DO id, and because we tend to serve traffic under https, I need the API call to happen under https as well.  

In particular, I need urls like this to work:
https://monarchinitiative.org/disease/DOID:2355.json

thanks!

**Comment by kevinschaper** [comment] 2016-02-29 22:11
Previously I'd been getting a list of HP ids from that url, but I don't see "phenotype_list" available as a part of that JSON document now.  I guess that strips the urgency for me, but supporting https should just be a small tweak to your apache config.

**Comment by kshefchek** [comment] 2016-02-29 22:16
We are working on getting a new ssl cert and should have the https site working again soon.  To fetch a list of phenotypes for a disease try:
http://monarchinitiative.org/disease/DOID:2355/phenotype_list.json

**Comment by harryhoch** [comment] 2016-02-29 22:17
Kevin:

Great to hear that you're working on this.  

@yuanzhou, please help @kevinschaper with any details of the PhenoGrid install as necessary.

**Comment by jnguyenx** [comment] 2016-02-29 22:34
In order to fully support https, we have to enable https on our underlying services as well (scigraph, golr, etc..).

Enabling https only on the monarch-app might be enough for you @kevinschaper but I prefer to do things properly even if it takes more time.

Expect an update in 2 weeks or so.

**Comment by harryhoch** [comment] 2016-02-29 22:59
@jnguyenx, understood. that it's better to do things properly. However, would it be possible to have https working for the monarch api on beta? This would allow @kevinschaper to move forward.

**Comment by jnguyenx** [comment] 2016-02-29 23:58
Yup I can do that this week!

**Comment by harryhoch** [comment] 2016-03-01 01:19
thanks!

**Comment by jxchong** [comment] 2016-03-01 04:28
Just writing to 2nd this request. We just realized we need to be able to use the API over https as well.  :)

**Comment by yuanzhou** [comment] 2016-03-01 14:07
@kevinschaper maybe we should have an talk before jumping into the details. I'll write you an email to introduce myself and details about Phenogrid. We've been integrating Phenogrid onto IMPC site and made many tweaks in a separate github branch. We haven't merged those changes to the Phenogrid master branch. Let's discuss via emails.

**Comment by jnguyenx** [comment] 2016-03-02 23:14
@harryhoch @kevinschaper  @yuanzhou 

https://beta.monarchinitiative.org/

**Comment by harryhoch** [comment] 2016-03-02 23:17
Thanks!

**Comment by yuanzhou** [comment] 2016-03-03 13:37
Thanks @jnguyenx . I tested and got the following errors in Chrome console:

![capture](https://cloud.githubusercontent.com/assets/195873/13495840/f0db8200-e11a-11e5-9e53-bd4dc7faf0dc.PNG)

I think as long as I change the config to let Phenogrid point to the https:// then we can address the second error. This also means that we'll need to have the production server running on https:// so we don't need to make further changes once push changes from beta to production.

**Comment by jmcmurry** [comment] 2016-03-07 05:49
Any update on this?

**Comment by yuanzhou** [comment] 2016-03-07 14:48
@jmcmurry I'm still getting this error.

**Comment by jmcmurry** [comment] 2016-03-07 20:30
@jnguyenx will implement on Beta, and then switch. May need to coordinate with Ethan.

**Comment by jnguyenx** [comment] 2016-03-09 21:37
@yuanzhou 

https is activated now on the services. If one tries to access via http, there's a redirect on https.
Phenogrid doesn't seem to follow the redirect and will throw the error you've already observed:

```
app.3760090….js:26 Mixed Content: The page at 'https://beta.monarchinitiative.org/disease/OMIM:605909' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://scigraph-ontology-dev.monarchinitiative.org/scigraph/dynamic/cliqueLeader/OMIM:605909.json'. This request has been blocked; the content must be served over HTTPS.st.cors.t.crossDomain.send @ app.3760090….js:26ct.extend.ajax @ app.3760090….js:25r @ app.3760090….js:74loaderBody @ OMIM:605909:113onload @ OMIM:605909:137
phenogrid-bundle.js:1 POST:http://beta.monarchinitiative.org/simsearch/phenotype
```

I'll force the configuration to https to try.

**Comment by jnguyenx** [comment] 2016-03-09 21:59
Ok it seems to work when I force https. I think that it is worth to make Phenogrid to follow the redirects, but I'll leave that decision to you.

Please test and let me know if everything works as intended. If yes we can foresee a switch soon.

**Comment by julesjacobsen** [comment] 2016-03-11 12:17
I think the server can be set directly  in the Phenogrid - clients just need to update it to use the https link as default and then it will work in both http and https sites without issue. I've made the change on the IMPC website so, once deployed it should work ok. Please let me know when https is also enabled on production as I'd obviously prefer to use this!

**Comment by jnguyenx** [comment] 2016-03-11 18:03
@harryhoch @yuanzhou I'm waiting for your blessing to go ahead ;-)

**Comment by harryhoch** [comment] 2016-03-11 21:48
@yuanzhou, please look into the indirect error, or just get it to use https directly.

**Comment by yuanzhou** [comment] 2016-03-14 15:55
@harryhoch @jnguyenx Errors are gone! Please pull the trigger to deploy to production. Thanks!

**Comment by jnguyenx** [comment] 2016-03-14 18:29
Hmm I've reached the quota to generate certs. I wasn't aware that there was a quota:

https://community.letsencrypt.org/t/public-beta-rate-limits/4772
- Rate limit on registrations per IP is currently 10 per 3 hours
- Rate limit on certificates per Domain is currently 5 per 7 days

I still need to generate certs for monarch-app-prod and solr-prod, I'll try later this week.

**Comment by jnguyenx** [comment] 2016-03-18 22:30
I've made the switch, let me know if you run in any issue.

**Closed as completed by jnguyenx** 2016-03-18 22:30 UTC
Labels: api and exports

**Comment by julesjacobsen** [comment] 2016-03-21 17:00
Works well on my local dev instance. Will switch dev.mousephenotype.org to use this for a while.
