### ISSUE TITLE
Provide additional guidance for user when a disease has no data

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#1254] opened 2016-05-20 04:56 UTC
see https://monarchinitiative.org/disease/Orphanet%3A93564

seems odd to me that a disease leaf node would have no data, @cmungall @drseb

**Comment by cmungall** [comment] 2016-06-08 19:55
it has no data http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=93564

I change the ticket title to be something about providing more guidance. E.g. asking if the user wants to go one level up. 

But I don't see what else to do here. Is this really a GSA milestone?

**Comment by jmcmurry** [comment] 2016-06-08 19:57
Not necessarily for GSA, but I was trying to identify little things that may need to be fixed that look wrong.

**Comment by jmcmurry** [comment] 2016-06-08 20:16
In this particular case, the term Orphanet:93564 is deprecated. What do we want our policy to be in such cases?

**Comment by cmungall** [comment] 2016-06-08 20:41
Wait, how can you tell it's deprecated? I don't see anything on the source page.  http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=93564

If it is deprecated, for orphanet it should come in that way via ordo and into mondo. But it doesn't appear to be deprecated

Treatment of deprecated classes should be uniform across all sources (which is not good, see #1276 )

**Comment by jmcmurry** [comment] 2016-06-08 20:44
I got the obsoleted status from EBI OLS [here](http://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_93564)

**Comment by jmcmurry** [comment] 2016-08-04 16:39
Given that the underlying issue was addressed, the remaining issue is now a duplicate of https://github.com/monarch-initiative/monarch-app/issues/1319 so closing

**Closed as completed by jmcmurry** 2016-08-04 16:39 UTC
