### ISSUE TITLE
Homolog gene labels not showing

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#929] opened 2015-08-23 11:58 UTC
on the homologs tab of http://monarchinitiative.org/gene/KEGG-hsa:4864
I see identifiers but not labels for ENSEMBL and other MOD genes

<img width="1440" alt="screen shot 2015-08-23 at 4 57 10 am" src="https://cloud.githubusercontent.com/assets/796636/9428113/7eb605ba-4953-11e5-985d-5b3ac7e4bb01.png">

**Comment by kshefchek** [comment] 2015-08-24 16:10
Duplicate of #879.  We are planning to fix this upstream but in the meantime we should be able to pull the labels from the evidence graph in the golr documents, will put this fix in the meantime.

**Comment by kshefchek** [comment] 2015-08-24 16:35
It looks like this information is not available in the golr documents.  So we will need to fix this at some point in the scigraph batchload or golr load.  Will use ticket #879 for tracking.

**Closed as completed by kshefchek** 2015-08-24 16:35 UTC
Labels: duplicate
