### ISSUE TITLE
need licenses on everything

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#762] opened 2015-06-12 14:42 UTC
We need to make sure we are consistent and clear about our licensing and attribution in all parts of the system. Julie, your first task!

**Comment by jmcmurry** [comment] 2015-06-12 19:08
Yay! Do you have a license preference or is choosing one part of the task?
Sometimes of course dependencies restrict the choices, but, in a blue sky
scenario?

**Comment by jgrethe** [comment] 2015-06-12 19:39
The license choice would partly be driven by OHSU’s policies (as the prime institution) and what was written into the original data sharing plan for the proposal. 

Cheers,
Jeff

**Comment by kltm** [comment] 2015-06-12 21:05
Would this be for data and/or code? I'd assume that the most permissive licenses available (CC-BY 4.0 and 3-clause BSD) would be the default stance. Tagging @cmungall .

**Comment by jmcmurry** [comment] 2015-07-08 18:08
This is a duplicate of https://github.com/monarch-initiative/monarch-app/issues/636

**Closed as completed by jmcmurry** 2015-07-08 18:08 UTC
Labels: duplicate
