### ISSUE TITLE
Phenotype analysis page not working: http://beta.monarchinitiative.org/analyze/phenotypes/

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-legacy#889] opened 2015-08-05 00:28 UTC
I go to http://beta.monarchinitiative.org/
and click on the "go to phenotype analysis" button
I select "abnormality of the ear" in the autocomplete box and click submit.
and there is an error in the resulting page
http://beta.monarchinitiative.org/analyze/phenotypes/?input_items=HP%3A0000598&mode=search&target_species=all&limit=100

```
Error: No results available! Please reload this widget later.
```

The complete contents of the console are:

```
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.
```

**Comment by cmungall** [comment] 2015-08-05 00:41
Showstopper

@kshefchek @yuanzhou @harryhoch is this related to recent refactoring around get/post?

**Comment by harryhoch** [comment] 2015-08-05 01:24
looking into it now.

**Comment by harryhoch** [comment] 2015-08-05 02:24
@cmungall, I'm not quite sure why we're seeing this now and we didn't earlier. the ajax calls are definitely written as sync now  - it's possible that this warning pops up on post and not get.

switching to async fixes an immediate problem, but creates the other problem of rewiring the code to catch the response appropriately. I'm not quite sure of how best to do that. @yuanzhou, @davism84, @kshefchek, any thoughts?

**Comment by kshefchek** [comment] 2015-08-05 04:31
The bug doesn't seem to be affecting all cases; for example, our [behave test](https://github.com/monarch-initiative/monarch-app/blob/1ce9ac00a8d9d21f48c2c6d811265c8f8a514794/tests/behave/maui_analyze.feature#L8) still passes.

Is there a reason we use a synchronous call rather than async?

**Comment by kshefchek** [comment] 2015-08-05 04:40
Also worth noting that this does not work on the production site either:
http://monarchinitiative.org/analyze/phenotypes/?input_items=HP%3A0000598&limit=100&target_species=

Is it expected that a single phenotype might not generate any similar diseases and/or model genes?  We get this XMLHttpRequest warning on all pages with the phenogrid (it is not related to the get/post configuration).  It's deprecated but should still work for the time being.

**Comment by kltm** [comment] 2015-08-05 05:05
There's a synchronous call in the client!? That should never ever be as is can literally lock up an entire browser and make it unusable (not even he browser buttons) until a response is returned. It didn't even know the jQuery allowed that anymore.

This traces back to phenogrid-bundle.js, so maybe a bug on that tracker?

**Comment by kshefchek** [comment] 2015-08-05 05:38
@kltm, phenogrid uses synchronous calls, but I agree we should refactor to use async and callbacks instead.  Have newer browsers solved these performance issues?  We have had these synchronous calls since I can remember and I've never noticed my browser locking up.

**Comment by kltm** [comment] 2015-08-05 06:02
I personally think having synchronous calls in there is a showstopper as you are literally one bad connection away from hanging somebody's browser completely. That, and it's not working.

This is not a performance issue, but rather a "threading" issue. [JavaScript history paragraph redacted.] Anyways, some browsers can use things like web workers for various tasks (which might be appropriate for a separate widget like this), but it's not something that is really here yet.

**Comment by harryhoch** [comment] 2015-08-05 11:42
@kltm, I don't think you're wrong, but it hasn't been a problem in the past. As @kshefchek said, we haven't noticed any lockup before.   I have started a refactor and will talk to @damiansm and @yuanzhou today to see what we can do.

**Comment by harryhoch** [comment] 2015-08-05 17:40
Preliminary fix in 'async' branch on phenogrid repo. @davism84 is testing. will generate a pull-request as soon as we are confident.

**Comment by yuanzhou** [comment] 2015-08-06 15:03
@harryhoch fixed this issue and I submitted a PR and merged the changes to master, also updated all the new changes to the release_v07312015 branch. 

@cmungall do you need me to create a new branch once the final release gets ready? I just feel the branch name release_v07312015 doesn't capture all the new changes made since July 31.

Please also close this issue once the monarch-app gets rebuilt and this error no longer shows up.

**Comment by yuanzhou** [comment] 2015-08-06 20:40
FYI, according to the meeting, I'll create a new branch with all new changes from phenogrid master branch, name it ‘release_2015-08-06’.

**Comment by yuanzhou** [comment] 2015-08-10 12:58
Still showing the `Error: No results available! Please reload this widget later.` but no error from phenogrid. I guess it's a data issue.

**Comment by kshefchek** [comment] 2015-08-10 16:17
It is expected behavior given no matches in the simsearch call.

**Closed as completed by kshefchek** 2015-08-10 16:17 UTC
Labels: bug
