### ISSUE TITLE
allow user to enter a list of ids for analyze

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#155] opened 2014-03-05 18:46 UTC
a user might want to put a string of ids (say, via a copy/paste action) instead of just typing/selecting matches.  can this be an optional/alternative input mode for the analyze query pages:
http://tartini.crbs.ucsd.edu/analyze

(of course, i know i can put this into the url directly, but might be a nice option.

**Comment by jmcmurry** [comment] 2015-10-10 00:50
Duplicate of a newer higher-level ticket here: https://github.com/monarch-initiative/monarch-app/issues/994

**Closed as completed by jmcmurry** 2015-10-10 00:50 UTC
Labels: duplicate, enhancement, web site front end, Analyze Phenotypes
